// Front-End/ReactJS/8. REACT HOOKS/client/src/components/Login/Login.js
function Login() {
    return (
        <section className="login">
            <form action="#" method="post">
                <fieldset>
                    <legend>Login</legend>
                    <p className="field">
                        <label htmlFor="username">Username</label>
                        <span className="input">
                            <input type="text" name="username" id="username" placeholder="Username" />
                            <span className="actions"></span>
                            <i className="fas fa-user"></i>
                        </span>
                    </p>
                    <p className="field">
                        <label htmlFor="password">Password</label>
                        <span className="input">
                            <input type="password" name="password" id="password" placeholder="Password" />
                            <span className="actions"></span>
                            <i className="fas fa-key"></i>
                        </span>
                    </p>
                    <input className="button submit" type="submit" value="Login" />
                </fieldset>
            </form>
        </section>
    );
}

export default Login;

// Front-End/Angular/06. Workshop - Modules and Routing/app/src/app/auth/login/login.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {

  constructor(private activatedRoute: ActivatedRoute, private router: Router, private authService: AuthService) {
    
  }

  loginHandler(): void {
    this.authService.user = {
      username: 'John'
    } as any;

    const returnUrl = this.activatedRoute.snapshot.queryParams['returnUrl'] || '/';

    this.router.navigate([returnUrl]);
  }
}

<form class="login" action="" method="post">
  <fieldset>
    <h2>Login Form</h2>

    <p class="field field-icon">
      <label for="email"
        ><span><i class="fas fa-envelope"></i></span
      ></label>
      <input
        class="input-error"
        type="email"
        name="email"
        id="email"
        placeholder="john.doe@gmail.com"
      />
    </p>
    <p class="error">Email is required!</p>
    <!-- <p class="error">
                Email is not valid!
            </p> -->

    <p class="field field-icon">
      <label for="password"
        ><span><i class="fas fa-lock"></i></span
      ></label>
      <input
        type="password"
        name="password"
        id="password"
        placeholder="******"
      />
    </p>
    <!-- <p class="error">
                Password is required!
            </p>
            <p class="error">
                Password must be at least 4 characters!
            </p> -->

    <button (click)="loginHandler()">Login</button>

    <p class="text-center">
      Have an account?
      <a href="#">Register</a>
    </p>
  </fieldset>
</form>
